### ISSUE TITLE
add css modules

### ISSUE THREAD

**Issue by phatpham9** [gorillab/reader-web#29]
https://medium.com/nulogy/how-to-use-css-modules-with-create-react-app-9e44bec2b5c2

**Comment by phatpham9** [comment]
close for now

**Comment by victorsilent** [comment]
You're my hero! I added scss on my project because you submit your webpack files. Thank you so much <3

**Comment by phatpham9** [comment]
@victorsilent does not remember that I did it. anyway you are welcome :)
